// config.bin - 03:35:38 03/22/15, generated in 0.02 seconds
// Generated by unRap v1.06 by Kegetys
// Separate rootclasses: Disabled, Automatic comments: Enabled

#define true	1
#define false	0

#define private		0
#define protected		1
#define public		2

#define TEast		0
#define TWest		1
#define TGuerrila		2
#define TCivilian		3
#define TSideUnknown		4
#define TEnemy		5
#define TFriendly		6
#define TLogic		7

class CfgPatches {
	class acex_ru_c_men {
		units[] = {"ACE_GUE_Soldier_RPG", "ACE_Ins_Soldier_RPG", "ACE_RU_Soldier_RPOM", "ACE_SoldierE_HMG", "ACE_SoldierE_HMGAG", "ACE_SoldierE_HMGAB", "ACE_SoldierE_AGS", "ACE_SoldierE_AGSAG", "ACE_SoldierE_AGSAB", "ACE_SoldierE_KonkursG", "ACE_SoldierE_KonkursAG", "ACE_RUS_Soldier_RPOM", "ACE_RUS_Soldier_Medic", "ACE_MVD_Soldier_RPOM"};
		weapons[] = {};
		requiredVersion = 1.54;
		requiredAddons[] = {"acex_ru_main", "CACharacters", "CACharacters2", "ace_main", "ace_sys_ruck", "ace_c_men", "acex_c_vehicle", "ace_sys_crewserved"};
		version = 1.14.0.76;
	};
};

class CfgAddons {
	class PreloadAddons {
		class acex_ru_c_men {
			list[] = {"acex_ru_c_men"};
		};
	};
};

class CfgVehicles {
	class Man;	// External class reference
	
	class CAManBase : Man {
		class HitPoints {
			class HitHead;	// External class reference
		};
		class TalkTopics;	// External class reference
	};
	
	class SoldierWB : CAManBase {
		class TalkTopics : TalkTopics {};
	};
	
	class SoldierEB : CAManBase {
		class TalkTopics : TalkTopics {};
	};
	
	class SoldierGB : CAManBase {
		class TalkTopics : TalkTopics {};
	};
	
	class USMC_Soldier_Base : SoldierWB {
		identityTypes[] = {"Language_EN_EP1", "Head_USMC", "USMC_Glasses"};
		
		class TalkTopics : TalkTopics {
			core_en = "Core_Full_E";
		};
	};
	
	class FR_Base : SoldierWB {
		identityTypes[] = {"Language_EN_EP1", "Head_USMC_Camo", "FR_Glasses"};
		
		class TalkTopics : TalkTopics {
			core_en = "Core_Full_E";
			core_tk = "Core_Full_E";
		};
	};
	
	class RU_Soldier_Base : SoldierEB {
		identityTypes[] = {"Language_RU", "Head_RU", "RU_Glasses"};
		accuracy = 2;	// accuracy needed to recognize type of this target
	};
	
	class RU_Soldier_Crew : RU_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.6;
			};
		};
	};
	
	class RU_Soldier : RU_Soldier_Base {};
	
	class RU_Soldier_GL : RU_Soldier_Base {};
	
	class RU_Soldier_Light : RU_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.6;
			};
		};
	};
	
	class ACE_RU_Soldier_RPOM : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_RIFLEMAN_RPOM;
		accuracy = 3.5;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, ACE_RPOM, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnWeapons[] = {ACE_AK74M, ACE_RPOM, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
	};
	
	class ACE_SoldierE_HMG : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_HMG;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_KORDProxy", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell"};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_KORDProxy", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell"};
	};
	
	class ACE_SoldierE_HMGAG : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_HMGAG;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_6T7TripodProxy", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", ACE_KORD_CSWDM};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_6T7TripodProxy", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", ACE_KORD_CSWDM};
	};
	
	class ACE_SoldierE_HMGAB : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_HMGAB;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell", ACE_KORD_CSWDM, ACE_KORD_CSWDM};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell", ACE_KORD_CSWDM, ACE_KORD_CSWDM};
	};
	
	class ACE_SoldierE_AGS : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_AGS;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_AGS30Proxy", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", ACE_AGS30_CSWDM};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_AGS30Proxy", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell"};
	};
	
	class ACE_SoldierE_AGSAG : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_AGSAG;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_AGS30TripodProxy", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell", ACE_AGS30_CSWDM};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_AGS30TripodProxy", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", ACE_AGS30_CSWDM};
	};
	
	class ACE_SoldierE_AGSAB : RU_Soldier_GL {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_AGSAB;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_Earplugs"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell", ACE_AGS30_CSWDM, ACE_AGS30_CSWDM};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_Earplugs"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", ACE_AGS30_CSWDM, ACE_AGS30_CSWDM};
	};
	
	class ACE_SoldierE_KonkursG : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_KONKURSG;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_KonkursTripodProxy"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell"};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_KonkursTripodProxy"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell"};
	};
	
	class ACE_SoldierE_KonkursAG : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_SOLDIERE_KONKURSAB;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "ACE_KonkursM_CSWDM", "ACE_KonkursM_CSWDM"};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "ACE_KonkursM_CSWDM"};
	};
	
	class ACE_RU_Soldier_Engineer : RU_Soldier {
		displayName = $STR_ACE_VDN_ACE_ENGINEER;
		picture = "\Ca\characters_E\data\Ico\i_eng_ca.paa";
		cost = 60000;
		accuracy = 3.9;	// accuracy needed to recognize type of this target
		
		// threat (VSoft, VArmor, VAir), how threatening vehicle is to unit types
		threat[] = {1, 0.5, 0.1};

		canDeactivateMines = true;
		engineer = 1;
		weapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "MineE", "MineE"};
		respawnWeapons[] = {ACE_AK74M, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "MineE"};
	};
	
	class MVD_Soldier_Base : SoldierEB {
		ACE_Stamina = 0.8;
		identityTypes[] = {"Language_RU", "Head_RU"};
		
		class TalkTopics : TalkTopics {
			core_en = "Core_Full_E";
			core_tk = "Core_Full_E";
		};
	};
	
	class MVD_Soldier : MVD_Soldier_Base {};
	
	class ACE_MVD_Soldier_RPOM : MVD_Soldier {
		displayName = $STR_ACE_VDN_ACE_OPERATOR_RPOM;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", ACE_RPOM};
		respawnWeapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", ACE_RPOM};
	};
	
	class RUS_Soldier_Base : SoldierEB {
		ACE_Stamina = 0.8;
		
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.6;
			};
		};
		identityTypes[] = {"Language_RU", "Head_RU_Camo", "RU_Glasses"};
		
		class TalkTopics : TalkTopics {
			core_en = "Core_Full_E";
			core_tk = "Core_Full_E";
		};
	};
	
	class RUS_Soldier1 : RUS_Soldier_Base {};
	
	class RUS_Soldier_GL : RUS_Soldier_Base {};
	
	class RUS_Soldier_Sab : RUS_Soldier_Base {
		scope = public;
		model = "\ca\characters2\Rus\Specnaz";
	};
	
	class ACE_RUS_Soldier_RPOM : RUS_Soldier_GL {
		displayName = $STR_ACE_VDN_ACE_ASSAULTMAN_RPOM;
		accuracy = 1000;	// accuracy needed to recognize type of this target
		weapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", ACE_RPOM};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_East", "HandGrenade_East", "HandGrenade_East", "Smokeshell"};
		respawnWeapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", ACE_RPOM};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "HandGrenade_East", "Smokeshell"};
	};
	
	class ACE_RUS_Soldier_Medic : RUS_Soldier1 {
		displayName = $STR_ACE_VDN_RUS_SOLDIER_MEDIC;
		accuracy = 3.7;	// accuracy needed to recognize type of this target
		attendant = true;
		weapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "Smokeshell", "Smokeshell", "SmokeshellOrange", "SmokeshellBlue"};
		respawnWeapons[] = {"ACE_AK105_Kobra", "ItemGPS", "NVGoggles", "Binocular", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "30Rnd_545x39_AK", "SmokeshellOrange", "SmokeshellBlue"};
	};
	
	class Ins_Soldier_Base : SoldierEB {
		//ACE_Stamina = 1.2;
		identityTypes[] = {"Language_RU", "Head_INS", "INS_Glasses"};
	};
	
	class Ins_Soldier_AT : Ins_Soldier_Base {};
	
	class ACE_Ins_Soldier_RPG : Ins_Soldier_AT {
		displayName = $STR_ACE_VDN_RPGGRENADIER;
		weapons[] = {AK_47_M, RPG7V, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", PG7V, PG7V, PG7V};
		respawnWeapons[] = {AK_47_M, RPG7V, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", PG7V, PG7V};
	};
	class INS_Soldier_1;	// External class reference
	
	class ACE_INS_Soldier_Engineer : INS_Soldier_1 {
		scope = public;
		engineer = 1;
		candeactivatemines = true;
		picture = "\Ca\characters_E\data\Ico\i_eng_ca.paa";
		displayName = $STR_ACE_VDN_ACE_ENGINEER;
		accuracy = 3.9;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_M3A1, "ACE_Earplugs", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_ALICE_Backpack"};
		magazines[] = {"ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "SmokeShellPurple", "SmokeShellYellow", "HandGrenade_East", "HandGrenade_East", "ACE_Pomz_M", "ACE_Pomz_M"};
		respawnWeapons[] = {ACE_M3A1, "ACE_Earplugs", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_ALICE_Backpack"};
		respawnMagazines[] = {"ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "SmokeShellPurple", "SmokeShellYellow", "ACE_Pomz_M", "ACE_Pomz_M"};
	};
	
	class CDF_Soldier_Base : SoldierWB {
		identityTypes[] = {"Language_CZ", "Head_CDF", "CDF_Glasses"};
		languages[] = {"CZ", "EN", "RU"};
		
		class TalkTopics : TalkTopics {
			core_en = "Core_Full_E";
			core_ru = "Core_Full";
		};
	};
	
	class CDF_Soldier : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_GL : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_Medic : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_Marksman : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_RPG : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_Strela : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_AR : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_MG : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_TL : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class CDF_Soldier_Pilot : CDF_Soldier_Base {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.7;
			};
		};
	};
	
	class CDF_Soldier_Engineer : CDF_Soldier {
		class HitPoints : HitPoints {
			class HitHead : HitHead {
				armor = 0.85;
			};
		};
	};
	
	class GUE_Soldier_Base : SoldierGB {
		identitytypes[] = {"Language_CZ", "Head_GUE", "INS_Glasses"};
	};
	class GUE_Soldier_AT;	// External class reference
	
	class ACE_GUE_Soldier_RPG : GUE_Soldier_AT {
		displayName = $STR_ACE_VDN_RPGGRENADIER;
		weapons[] = {AK_47_M, RPG7V, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		magazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", PG7V, PG7V, PG7V};
		respawnWeapons[] = {AK_47_M, RPG7V, "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio"};
		respawnMagazines[] = {"30Rnd_762x39_AK47", "30Rnd_762x39_AK47", "30Rnd_762x39_AK47", PG7V, PG7V};
	};
	class GUE_Soldier_3;	// External class reference
	
	class ACE_GUE_Soldier_Engineer : GUE_Soldier_3 {
		engineer = 1;
		candeactivatemines = true;
		picture = "\Ca\characters_E\data\Ico\i_eng_ca.paa";
		displayName = $STR_ACE_VDN_ACE_ENGINEER;
		accuracy = 3.9;	// accuracy needed to recognize type of this target
		weapons[] = {ACE_M3A1, "ACE_Earplugs", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_ALICE_Backpack"};
		magazines[] = {"ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "SmokeShellPurple", "SmokeShellYellow", "HandGrenade_East", "HandGrenade_East", "ACE_Pomz_M", "ACE_Pomz_M"};
		respawnWeapons[] = {ACE_M3A1, "ACE_Earplugs", "Throw", "Put", "ItemMap", "ItemCompass", "ItemWatch", "ItemRadio", "ACE_ALICE_Backpack"};
		respawnMagazines[] = {"ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "ACE_30Rnd_1143x23_B_M3", "SmokeShellPurple", "SmokeShellYellow", "ACE_Pomz_M", "ACE_Pomz_M"};
	};
};

class CfgGroups {
	class East {
		class RU {
			class ACE_CSW_Infantry {
				name = $STR_ACE_GN_CSWTEAM;
				
				class ACE_RU_KordTeam {
					name = $STR_ACE_VDN_ACE_KORDMGT;
					
					class Unit0 {
						side = TEast;
						vehicle = "ACE_SoldierE_HMG";
						rank = SERGEANT;
						position[] = {0, "+6", 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ACE_SoldierE_HMGAG";
						rank = CORPORAL;
						position[] = {-2, "+4", 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ACE_SoldierE_HMGAB";
						rank = PRIVATE;
						position[] = {"+2", "+4", 0};
					};
				};
				
				class ACE_RU_AGS30Team {
					name = $STR_ACE_VDN_ACE_AGS30MGT;
					
					class Unit0 {
						side = TEast;
						vehicle = "ACE_SoldierE_AGS";
						rank = SERGEANT;
						position[] = {0, "+6", 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ACE_SoldierE_AGSAG";
						rank = CORPORAL;
						position[] = {-2, "+4", 0};
					};
					
					class Unit2 {
						side = TEast;
						vehicle = "ACE_SoldierE_AGSAB";
						rank = PRIVATE;
						position[] = {"+2", "+4", 0};
					};
				};
				
				class ACE_RU_KonkursTeam {
					name = $STR_ACE_VDN_ACE_KONKURST;
					
					class Unit0 {
						side = TEast;
						vehicle = "ACE_SoldierE_KonkursG";
						rank = SERGEANT;
						position[] = {0, "+6", 0};
					};
					
					class Unit1 {
						side = TEast;
						vehicle = "ACE_SoldierE_KonkursAG";
						rank = CORPORAL;
						position[] = {-2, "+4", 0};
					};
				};
			};
		};
	};
};
