sleep 1;
soundfx say3D "mortar1";
sleep 2;
soundfx say3D "credits_boom_2";
sleep 2;
soundfx say3D "mortar1";
sleep 2;
soundfx say3D "credits_boom_1";
sleep 3;
soundfx say3D "mortar1";
sleep 2;
soundfx say3D "missile_impact";
smoke = "ARTY_SmokeShellWhite" createVehicle (getMarkerPos "smokescreen");
sleep 5;
[West,"HQ"] sideChat "Rounds complete, you're clear to move up, out.";
playSound "beep"; 
playSound "radionoise1";
smoke = "ARTY_SmokeShellWhite" createVehicle (getMarkerPos "smokescreen");
sleep 5;
Leader alpha sideChat "Copy that, we're moving into the village to clean up, out.";
playSound "beep"; 
playSound "radionoise1";
smoke = "ARTY_SmokeShellWhite" createVehicle (getMarkerPos "smokescreen");
sleep 2;
artydone = true;