#include "script_component.hpp"
#include "Script_SightAdjustmentConfig.hpp"

switch (toLower ACE_SYS_SA_WCFG_ELEVATION_UNITS) do {
	case "mil": { ACE_SYS_SA_SET_CURELEVATION_DEG(deg ((ACE_SYS_SA_CURELEVATION - ACE_SYS_SA_WCFG_DEFAULTELEVATION)/1000)) };
	case "mil_e": { ACE_SYS_SA_SET_CURELEVATION_DEG((ACE_SYS_SA_CURELEVATION - ACE_SYS_SA_WCFG_DEFAULTELEVATION)*0.06) };
	case "moa": { ACE_SYS_SA_SET_CURELEVATION_DEG((ACE_SYS_SA_CURELEVATION - ACE_SYS_SA_WCFG_DEFAULTELEVATION)/60) };
	case "deg": { ACE_SYS_SA_SET_CURELEVATION_DEG(ACE_SYS_SA_CURELEVATION - ACE_SYS_SA_WCFG_DEFAULTELEVATION) };
	default { ACE_SYS_SA_SET_CURELEVATION_DEG(ACE_SYS_SA_CURELEVATION - ACE_SYS_SA_WCFG_DEFAULTELEVATION) };
};

switch (toLower ACE_SYS_SA_WCFG_WINDAGE_UNITS) do {
	case "mil": { ACE_SYS_SA_SET_CURWINDAGE_DEG(deg ((ACE_SYS_SA_CURWINDAGE - ACE_SYS_SA_WCFG_DEFAULTWINDAGE)/1000)) };
	case "mil_e": { ACE_SYS_SA_SET_CURWINDAGE_DEG((ACE_SYS_SA_CURWINDAGE - ACE_SYS_SA_WCFG_DEFAULTWINDAGE)*0.06) };
	case "moa": { ACE_SYS_SA_SET_CURWINDAGE_DEG((ACE_SYS_SA_CURWINDAGE - ACE_SYS_SA_WCFG_DEFAULTWINDAGE)/60) };
	case "deg": { ACE_SYS_SA_SET_CURWINDAGE_DEG(ACE_SYS_SA_CURWINDAGE - ACE_SYS_SA_WCFG_DEFAULTWINDAGE) };
	default { ACE_SYS_SA_SET_CURWINDAGE_DEG(ACE_SYS_SA_CURWINDAGE - ACE_SYS_SA_WCFG_DEFAULTWINDAGE) };
};