// by Xeno
private ["_vec"];

_vec = _this select 0;
clearMagazineCargo _vec;
clearWeaponCargo _vec;

_vec addweaponcargo ["ACE_ParachutePack",50];
_vec addweaponcargo ["M9",1];
_vec addweaponcargo ["M9SD",1];
_vec addweaponcargo ["Colt1911",1];
_vec addweaponcargo ["ACE_Glock17",1];
_vec addweaponcargo ["ACE_Glock18",1];
_vec addweaponcargo ["ACE_Flaregun",1];
_vec addweaponcargo ["M16A2",1];
_vec addweaponcargo ["M16A2GL",1];
_vec addweaponcargo ["M16A4",1];
_vec addweaponcargo ["M16A4_GL",1];
_vec addweaponcargo ["M16A4_ACG",1];
_vec addweaponcargo ["M16A4_ACG_GL",1];
_vec addweaponcargo ["ACE_M16A4_Iron",1];

_vec addweaponcargo ["M4A1",1];
_vec addweaponcargo ["ACE_M4A1_GL",1];
_vec addweaponcargo ["ACE_M4A1_GL_SD",1];
_vec addweaponcargo ["M4A1_HWS_GL",1];
_vec addweaponcargo ["M4A1_HWS_GL_camo",1];
_vec addweaponcargo ["M4A1_HWS_GL_SD_Camo",1];
_vec addweaponcargo ["M4A1_RCO_GL",1];
_vec addweaponcargo ["M4A1_Aim",1];
_vec addweaponcargo ["M4A1_Aim_camo",1];
_vec addweaponcargo ["M4A1_AIM_SD_camo",1];

_vec addweaponcargo ["ACE_SOC_M4A1_Aim",1];
_vec addweaponcargo ["ACE_SOC_M4A1_AIM_SD",1];
_vec addweaponcargo ["ACE_SOC_M4A1_GL",1];
_vec addweaponcargo ["ACE_SOC_M4A1",1];
_vec addweaponcargo ["ACE_SOC_M4A1_GL_SD",1];
_vec addweaponcargo ["ACE_SOC_M4A1_Eotech",1];
_vec addweaponcargo ["ACE_SOC_M4A1_GL_13",1];
_vec addweaponcargo ["ACE_SOC_M4A1_GL_EOTECH",1];
_vec addweaponcargo ["ACE_SOC_M4A1_SD_9",1];
_vec addweaponcargo ["ACE_SOC_M4A1_SHORTDOT",1];
_vec addweaponcargo ["ACE_SOC_M4A1_SHORTDOT_SD",1];
_vec addweaponcargo ["ACE_SOC_M4A1_RCO_GL",1];
_vec addweaponcargo ["ACE_SOC_M4A1_GL_AIMPOINT",1];

_vec addweaponcargo ["ACE_M4A1_ACOG",1];
_vec addweaponcargo ["ACE_M4A1_ACOG_SD",1];
_vec addweaponcargo ["ACE_M4A1_Aim_SD",1];
_vec addweaponcargo ["ACE_M4A1_Eotech",1];

_vec addweaponcargo ["ACE_FAL_Para",1];
_vec addweaponcargo ["ACE_SA58",1];

_vec addweaponcargo ["G36a",1];
_vec addweaponcargo ["G36c",1];
_vec addweaponcargo ["G36_C_SD_eotech",1];
_vec addweaponcargo ["G36k",1];

_vec addweaponcargo ["M1014",1];

_vec addweaponcargo ["MP5A5",1];
_vec addweaponcargo ["MP5SD",1];
_vec addweaponcargo ["ACE_MP5A4",1];
_vec addweaponcargo ["ACE_UMP45",1];
_vec addweaponcargo ["ACE_UMP45_SD",1];

_vec addweaponcargo ["M8_carbine",1];
_vec addweaponcargo ["M8_carbineGL",1];
_vec addweaponcargo ["M8_compact",1];

_vec addweaponcargo ["MG36",1];
_vec addweaponcargo ["Mk_48",1];
_vec addweaponcargo ["M240",1];
_vec addweaponcargo ["ACE_M240G_M145",1];
_vec addweaponcargo ["ACE_M60",1];
_vec addweaponcargo ["M249",1];
_vec addweaponcargo ["ACE_M249Para",1];
_vec addweaponcargo ["ACE_M249Para_M145",1];
_vec addweaponcargo ["M8_SAW",1];

_vec addweaponcargo ["M24",1];
_vec addweaponcargo ["DMR",1];
_vec addweaponcargo ["M107",1];
_vec addweaponcargo ["M40A3",1];
_vec addweaponcargo ["M4SPR",1];
_vec addweaponcargo ["ACE_M4SPR_SD",1];
_vec addweaponcargo ["M8_sharpshooter",1];
_vec addweaponcargo ["ACE_M109",1];
_vec addweaponcargo ["ACE_M110",1];
_vec addweaponcargo ["ACE_M110_SD",1];
_vec addweaponcargo ["ACE_TAC50",1];
_vec addweaponcargo ["ACE_TAC50_SD",1];

_vec addweaponcargo ["M136",1];
_vec addweaponcargo ["SMAW",1];

_vec addweaponcargo ["ACE_M32",1];
_vec addweaponcargo ["ACE_M79",1];

_vec addweaponcargo ["ACE_GlassesSpectacles",1];
_vec addweaponcargo ["ACE_GlassesRoundGlasses",1];
_vec addweaponcargo ["ACE_GlassesSunglasses",1];
_vec addweaponcargo ["ACE_GlassesBlackSun",1];
_vec addweaponcargo ["ACE_GlassesBlueSun",1];
_vec addweaponcargo ["ACE_GlassesRedSun",1];
_vec addweaponcargo ["ACE_GlassesGreenSun",1];
_vec addweaponcargo ["ACE_GlassesLHD_glasses",1];
_vec addweaponcargo ["ACE_GlassesLHD_glasses",1];
_vec addweaponcargo ["ACE_GlassesTactical",1];
_vec addweaponcargo ["ACE_GlassesGasMask_US",1];
_vec addweaponcargo ["ACE_GlassesBalaklava",1];
_vec addweaponcargo ["ACE_Earplugs",1];
_vec addweaponcargo ["ACE_Kestrel4500",1];

_vec addweaponcargo ["Laserdesignator",1];
_vec addweaponcargo ["ACE_Rangefinder_OD",1];
_vec addweaponcargo ["Binocular",1];
_vec addweaponcargo ["NVGoggles",1];
_vec addweaponcargo ["JAVELIN",1];
_vec addweaponcargo ["STINGER",1];
_vec addmagazinecargo ["ACE_Battery_Rangefinder",50];
_vec addmagazinecargo ["HandGrenade_West",50];
_vec addmagazinecargo ["HandGrenade_Stone",50];
_vec addmagazinecargo ["Smokeshell",50];
_vec addmagazinecargo ["Smokeshellred",50];
_vec addmagazinecargo ["Smokeshellgreen",50];
_vec addmagazinecargo ["SmokeShellYellow",50];
_vec addmagazinecargo ["SmokeShellOrange",50];
_vec addmagazinecargo ["SmokeShellPurple",50];

_vec addmagazinecargo ["ace_flashbang",50];
_vec addmagazinecargo ["ace_m84",50];
_vec addmagazinecargo ["ace_m7a3",50];
_vec addmagazinecargo ["ace_m34",50];
_vec addmagazinecargo ["ACE_IRStrobe",50];
_vec addmagazinecargo ["ACE_M86PDM",50];
_vec addmagazinecargo ["ACE_M2SLAM_M",50];

_vec addmagazinecargo ["30Rnd_9x19_MP5",50];
_vec addmagazinecargo ["30Rnd_9x19_MP5SD",50];
_vec addmagazinecargo ["ACE_25Rnd_1143x23_B_UMP45",50];
_vec addmagazinecargo ["7Rnd_45ACP_1911",50];
_vec addmagazinecargo ["15Rnd_9x19_M9",50];
_vec addmagazinecargo ["15Rnd_9x19_M9SD",50];
_vec addmagazinecargo ["ACE_33Rnd_9x19_G18",50];
_vec addmagazinecargo ["ACE_17Rnd_9x19_G17",50];
_vec addmagazinecargo ["20Rnd_556x45_Stanag",50];
_vec addmagazinecargo ["30Rnd_556x45_Stanag",50];
_vec addmagazinecargo ["ACE_30Rnd_556x45_T_Stanag",50];
_vec addmagazinecargo ["30Rnd_556x45_StanagSD",50];
_vec addmagazinecargo ["ACE_20Rnd_762x51_B_FAL",50];
_vec addmagazinecargo ["ACE_30Rnd_762x51_B_FAL",50];
_vec addmagazinecargo ["30Rnd_556x45_G36",50];
_vec addmagazinecargo ["200Rnd_556x45_M249",50];
_vec addmagazinecargo ["ACE_200Rnd_556x45_T_M249",50];
_vec addmagazinecargo ["100Rnd_556x45_BetaCMag",50];
_vec addmagazinecargo ["8Rnd_B_Beneli_74Slug",50];
_vec addmagazinecargo ["ACE_8Rnd_12Ga_Slug",50];
_vec addmagazinecargo ["ACE_8Rnd_12Ga_Buck00",50];
_vec addmagazinecargo ["ACE_9Rnd_12Ga_Slug",50];
_vec addmagazinecargo ["ACE_9Rnd_12Ga_Buck00",50];
_vec addmagazinecargo ["5Rnd_762x51_M24",50];
_vec addmagazinecargo ["ACE_5Rnd_762x51_T_M24",50];
_vec addmagazinecargo ["20Rnd_762x51_DMR",50];
_vec addmagazinecargo ["ACE_20Rnd_762x51_T_DMR",50];
_vec addmagazinecargo ["10Rnd_127x99_M107",3];
_vec addmagazinecargo ["ACE_10Rnd_127x99_T_m107",3];
_vec addmagazinecargo ["ACE_5Rnd_25x59_HEDP_Barrett",3];
_vec addmagazinecargo ["ACE_20Rnd_762x51_SB_M110",50];
_vec addmagazinecargo ["ACE_20Rnd_762x51_S_M110",50];
_vec addmagazinecargo ["ACE_20Rnd_762x51_T_M110",50];
_vec addmagazinecargo ["ACE_5Rnd_127x99_B_TAC50",3];
_vec addmagazinecargo ["ACE_5Rnd_127x99_S_TAC50",3];
_vec addmagazinecargo ["ACE_5Rnd_127x99_T_TAC50",3];
_vec addmagazinecargo ["100Rnd_762x51_M240",50];
_vec addmagazinecargo ["1Rnd_HE_M203",50];
_vec addmagazinecargo ["ace_1rnd_cs_m203",50];
_vec addmagazinecargo ["ACE_6Rnd_40mm_M32",50];
_vec addmagazinecargo ["FlareWhite_M203",50];
_vec addmagazinecargo ["FlareGreen_M203",50];
_vec addmagazinecargo ["FlareRed_M203",50];
_vec addmagazinecargo ["ACE_SSWhite_M203",50];
_vec addmagazinecargo ["ACE_SSGreen_M203",50];
_vec addmagazinecargo ["ACE_SSRed_M203",50];
_vec addmagazinecargo ["ACE_SSYellow_M203",50];
_vec addmagazinecargo ["1Rnd_SmokeRed_M203",50];
_vec addmagazinecargo ["1Rnd_SmokeGreen_M203",50];
_vec addmagazinecargo ["1Rnd_SmokeYellow_M203",50];
_vec addmagazinecargo ["1Rnd_Smoke_M203",50];
_vec addMagazineCargo ["ACE_SSWhite_FG",50];
_vec addMagazineCargo ["ACE_SSRed_FG",50];
_vec addMagazineCargo ["ACE_SSGreen_FG",50];
_vec addMagazineCargo ["ACE_SSYellow_FG",50];
//_vec addmagazinecargo ["M136",10];
_vec addmagazinecargo ["SMAW_HEAA",3];
_vec addmagazinecargo ["SMAW_HEDP",3];
_vec addmagazinecargo ["ACE_SMAW_Spotting",30];
_vec addmagazinecargo ["Pipebomb",30];
_vec addmagazinecargo ["Mine",30];
_vec addmagazinecargo ["ACE_Claymore_M",30];
_vec addmagazinecargo ["ACE_BBetty_M",30];
_vec addmagazinecargo ["ACE_TripFlare_M",30];
_vec addmagazinecargo ["Laserbatteries",20];
_vec addWeaponCargo ["ACE_Javelin_CLU",1];
_vec addmagazinecargo ["STINGER",2];
_vec addmagazinecargo ["ACE_Knicklicht_R",50];
_vec addmagazinecargo ["ACE_Knicklicht_W",50];
_vec addmagazinecargo ["ACE_Knicklicht_Y",50];
_vec addmagazinecargo ["ACE_Knicklicht_B",50];
_vec addmagazinecargo ["ACE_Knicklicht_IR",50];

if (true) exitWith {};
