	#define SIDE "WEST"
	#define SIDE_STARTPOS DEFAULT_STARTPOS_WEST

	#define UNIT_SL "US_Soldier_SL_EP1"
	#define UNIT_MEDIC "US_Soldier_Medic_EP1"
	#define UNIT_TL "US_Soldier_TL_EP1"
	#define UNIT_RIFLEMAN "US_Soldier_EP1"
	#define UNIT_AR "US_Soldier_AR_EP1"
	#define UNIT_GL "US_Soldier_GL_EP1"
	#define UNIT_MG "US_Soldier_MG_EP1"
	#define UNIT_OFFICER "US_Soldier_Officer_EP1"
	#define UNIT_CREW "US_Soldier_Crew_EP1"
	#define UNIT_PILOT "US_Soldier_Pilot_EP1"
	#define UNIT_SNIPER "US_Soldier_Sniper_EP1"
	#define UNIT_SPOTTER "US_Soldier_Spotter_EP1"
	#define UNIT_LAT "US_Soldier_LAT_EP1"

	#define UNIT_AAR "US_Soldier_AAR_EP1"
	#define UNIT_AT "US_Soldier_AT_EP1"
	#define UNIT_AAT "US_Soldier_AAT_EP1"
	#define UNIT_AMG "US_Soldier_AMG_EP1"
	#define UNIT_ENGINEER "US_Soldier_Engineer_EP1"
	#define UNIT_DM "US_Soldier_Marksman_EP1"

	#define UNIT_SF_L "US_Delta_Force_TL_EP1"
	#define UNIT_SF_AR "US_Delta_Force_AR_EP1"
	#define UNIT_SF_GL "US_Delta_Force_Assault_EP1"
	#define UNIT_SF_DMR "US_Delta_Force_Marksman_EP1"
	#define UNIT_SF_SAB "US_Delta_Force_EP1"
	#define UNIT_SF_MEDIC "US_Delta_Force_Medic_EP1"