/* ----------------------------------------------------------------------------
Function: ACE_fnc_turretFeature

Description:
	Function to retrieve a turret feature

Parameters:
	-

Returns:
		TurretFeature

Examples:
	(begin example)
		-
	(end)

Author:
	(c) Rocko 2010
---------------------------------------------------------------------------- */
// fnc_TurretFeature.sqf

/* DO NOT EDIT THIS FILE */
/* SUBMISSIONS AND SUGGESTIONS: Contact author first ! */

#include "script_component.hpp"

PARAMS_2(_u,_f);

private "_v";
_v = vehicle _u;

#define __cfg (configFile >> "CfgVehicles" >> (typeof _v) >> "turrets")

_tp = [];
_tc  = count __cfg;
if (_tc > 0) then {
	for "_mti" from 0 to (_tc-1) do {
		_tp set [count _tp, [_mti]];
		_st = (__cfg select _mti) >> "turrets";
		_stc = count _st;
		if (_stc > 0) then {
			for "_sti" from 0 to (_stc-1) do {
				_stp = _st select _sti;
				_tp set [count _tp, [_mti,_sti]];
			};
		};
	};
};

_ptp = [];
{if (_u == _v turretUnit _x) then {_ptp = _x}} foreach _tp;
if (_u == driver _v) then { _ptp = [-1]; };
if ((assignedVehicleRole _u) in ["CARGO"]) exitWith { false }; // Cargo seats have NO features enabled.

_tf = false;
_ft = -1;
if (count _ptp > 1) then {
	_ft = getNumber((((__cfg select (_ptp select 0)) >> "turrets") select (_ptp select 1)) >> _f);
	if (_ft == 1) then { _tf = true; };
} else {
	if ((_ptp select 0) < 0) then {
		_ft = getNumber(configFile >> "CfgVehicles" >> typeOf _v >> _f);
		if (_ft == 1) then { _tf = true; };
	} else {
		_ft = getNumber(__cfg select (_ptp select 0) >> _f);
		if (_ft == 1) then { _tf = true; };
	};
};

TRACE_3("",_tp,_ptp,_tf);

_tf