rem run once to copy x_setup.sqf and x_macros.sqf to all directories that need it
copy x_setup.sqf x_server /Y
copy x_setup.sqf x_server\x_f /Y
copy x_setup.sqf AAHALO /Y
copy x_setup.sqf AAHALO\scripts /Y
copy x_setup.sqf scripts /Y
copy x_setup.sqf x_client /Y
copy x_setup.sqf x_client\x_f /Y
copy x_setup.sqf x_common /Y
copy x_setup.sqf x_common\x_f /Y
copy x_setup.sqf x_dlg /Y
copy x_setup.sqf x_missions /Y
copy x_setup.sqf x_missions\m /Y
copy x_setup.sqf x_missions\moa /Y
copy x_setup.sqf x_missions\common /Y
copy x_setup.sqf x_msg /Y
copy x_setup.sqf x_bikb /Y
copy x_setup.sqf IntroAnim /Y
copy x_setup.sqf x_mtmissions /Y
copy x_setup.sqf BIS_Effects /Y
copy x_setup.sqf spect /Y
copy x_macros.sqf x_server /Y
copy x_macros.sqf x_server\x_f /Y
copy x_macros.sqf x_client /Y
copy x_macros.sqf x_client\x_f /Y
copy x_macros.sqf x_common /Y
copy x_macros.sqf x_common\x_f /Y
copy x_macros.sqf AAHALO /Y
copy x_macros.sqf AAHALO\scripts /Y
copy x_macros.sqf scripts /Y
copy x_macros.sqf x_dlg /Y
copy x_macros.sqf x_missions /Y
copy x_macros.sqf x_missions\m /Y
copy x_macros.sqf x_missions\moa /Y
copy x_macros.sqf x_missions\common /Y
copy x_macros.sqf x_msg /Y
copy x_macros.sqf x_bikb /Y
copy x_macros.sqf IntroAnim /Y
copy x_macros.sqf x_mtmissions /Y
copy x_macros.sqf BIS_Effects /Y
copy x_macros.sqf spect /Y
rem cd ..